DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCIDENLINEA_001;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCIDENLINEA_001 
(
NUMERO_TELEFONICO VARCHAR(11)
)  PRIMARY INDEX(NUMERO_TELEFONICO) ;

delete from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001;
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('969774133');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('949086551');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('949517105');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('988080245');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('913987253');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('964417611');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('17226315');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('974016329');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('996371172');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('974539171');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('943454955');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('991821880');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('954837669');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('948347170');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('963599487');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('914721247');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('982881165');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('971877779');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('972453289');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('971982824');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('979825864');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('984589884');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('932954589');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('937537652');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('947506059');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('912326598');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('945679437');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('920706114');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('944985817');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('980172432');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('966086631');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('920612910');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('937783973');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('985942982');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('984952772');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('981787025');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('941993679');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('990146054');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('968147608');
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 ('965382031');

drop table PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002  AS
(
select a.*
,DOS.CUSTOMER_KEY
,subscriber_key
,original_activation_date
,DOS.ACTIVATION_DATE 
,DOS.SUBSCRIBER_STATUS_DATE 
,DOS.SUBSCRIBER_STATUS_KEY 
,S.SUBSCRIBER_STATUS_DESC
,CINCO.ADDRESS_KEY DIRECCION
,CASE WHEN  DOS.LOB_TYPE = 'WRLS' THEN 'MOVIL'
	  WHEN  DOS.LOB_TYPE = 'VOIC' THEN 'FIJA'
END TIPO_PLAN
,CASE 
	WHEN SEIS.customer_type_id='C' THEN 'RUC' ELSE NVL(OCHO.IDENTIFICATION_1_TYPE_CODE,NUEVE.IDENTIFICATION_1_TYPE_CODE) END TIPO_DOC_ID_AMD, 
	CASE 
	WHEN SEIS.customer_type_id='C' THEN TRES.RUT_ID ELSE NVL(OCHO.IDENTIFICATION_DOCUMENT_1_NUMB,NUEVE.IDENTIFICATION_DOCUMENT_1_NUMB) END NUMERO_DOC_ID_AMD, 
	CAST(CASE WHEN SEIS.customer_type_id='C' THEN TRES.customer_legal_name ELSE NVL(OCHO.FIRST_NAME,NUEVE.FIRST_NAME) END AS char(150))NOMBRES_AMD, 
	CAST(CASE WHEN SEIS.customer_type_id='C' THEN '' ELSE NVL(OCHO.LAST_NAME,NUEVE.LAST_NAME) END AS char(150)) APELLIDOS_AMD
from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 A
	inner join PE_PROD_LZ_DATA.ALDM_SUBSCRIBER  DOS
	on a.NUMERO_TELEFONICO  = DOS.PRIMARY_RESOURCE_VALUE 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CUSTOMER TRES ON DOS.CUSTOMER_KEY = TRES.CUSTOMER_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CUSTOMER_SUB_TYPE SEIS ON TRES.customer_sub_type_key = SEIS.customer_sub_type_key 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CUSTOMER_CONTACT_REL SIETE ON DOS.CUSTOMER_KEY = SIETE.CUSTOMER_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CONTACT OCHO ON SIETE.CONTACT_KEY = OCHO.CONTACT_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CONTACT NUEVE ON NUEVE.CONTACT_KEY = DOS.CONTACT_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_CONTACT CUATRO ON TRES.CRM_CUSTOMER_MAIN_CONTACT_SOUR = CUATRO.CONTACT_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_ADDRESS CINCO ON CUATRO.MAIN_ADDRESS_KEY = CAST(CINCO.ADDRESS_KEY AS DECIMAL(20,0) )  
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_SUBSCRIBER_STATUS S ON DOS.SUBSCRIBER_STATUS_KEY = CAST(S.SUBSCRIBER_STATUS_KEY AS DECIMAL(20,0) )  
)WITH DATA  PRIMARY INDEX(NUMERO_TELEFONICO);


DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_003;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_003  AS 
(
	SELECT BASE.* FROM
		(
			sel A.SUBSCRIBER_KEY
			,A.NUMERO_TELEFONICO
			,B.ASSIGNED_PRODUCT_KEY
			,B.PRODUCT_KEY
			,B.PRODUCT_OFFER_KEY
			,B.SERVICE_TYPE
			,B.START_DATE
			,B.END_DATE 
			,ASSIGNED_PRODUCT_STATUS_KEY
			,ASSIGNED_PRODUCT_STATE_KEY
			,ROW_NUMBER() OVER (PARTITION BY  A.SUBSCRIBER_KEY,a.NUMERO_TELEFONICO
			  ORDER BY B.ASSIGNED_PRODUCT_KEY DESC) ORD 
			from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002 A 
			INNER JOIN PE_PROD_LZ_DATA.ALDM_ASSIGNED_PRODUCT B 
				ON A.SUBSCRIBER_KEY=B.SUBSCRIBER_KEY
			WHERE B.SERVICE_TYPE='VOIC'
			AND ASSIGNED_PRODUCT_STATE_KEY='1097'
	) BASE WHERE ORD=1
)WITH DATA PRIMARY INDEX(ASSIGNED_PRODUCT_KEY,SUBSCRIBER_KEY,NUMERO_TELEFONICO);

DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_004;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_004 AS 
(
	SEL A.SUBSCRIBER_KEY
		,A.NUMERO_TELEFONICO
		--,A.ASSIGNED_PRODUCT_KEY
		--,VW1.DEFAULT_VALUE,
	--,CASE WHEN VW1.DEFAULT_VALUE='TUPSPREP' THEN 'TUPS' ELSE VW1.DEFAULT_VALUE END AS MACROSEGMENTO, 
	--CASE WHEN CUSTOMER_TYPE_DESC='Residencial' THEN 'TUP PROPIO' ELSE CUSTOMER_TYPE_DESC END AS SEGMENTOCUENTA
	--,'TPE' AS PRODUCTO, 
	--VW.DEFAULT_VALUE DEFVAL_PR 
	FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_003 A 
	INNER JOIN PE_PROD_ESL_VIEW.VW_PRODUCT_CATALOG_PARAMS1 VW1 
	ON VW1.PRODUCT_CATALOG_KEY=A.PRODUCT_OFFER_KEY AND VW1.product_parameter_name ='Product Classification' 
	INNER JOIN PE_PROD_ESL_VIEW.VW_PRODUCT_CATALOG_PARAMS1 VW 
	ON VW.PRODUCT_CATALOG_KEY=A.PRODUCT_OFFER_KEY  AND VW.product_parameter_name ='Product'
	AND VW1.DEFAULT_VALUE IN ('TUPS','TUPSPREP')
)WITH DATA PRIMARY INDEX(SUBSCRIBER_KEY,NUMERO_TELEFONICO);
 
--SELECT * FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002 
DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_005;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_005 AS 
( 
	select A.NUMERO_TELEFONICO
	,A.CUSTOMER_KEY
	,A.SUBSCRIBER_KEY
	,A.ORIGINAL_ACTIVATION_DATE
	,A.ACTIVATION_DATE
	,A.SUBSCRIBER_STATUS_DATE
	,A.SUBSCRIBER_STATUS_KEY
	,A.SUBSCRIBER_STATUS_DESC
	,A.DIRECCION
	,A.TIPO_PLAN
	,A.TIPO_DOC_ID_AMD
	--,A.NUMERO_DOC_ID_AMD
	,A.NOMBRES_AMD
	,A.APELLIDOS_AMD
	,CASE 
		WHEN A.TIPO_DOC_ID_AMD = 'C' THEN LPAD(A.NUMERO_DOC_ID_AMD,12,'0')
		WHEN A.TIPO_DOC_ID_AMD = 'DNI' THEN LPAD(A.NUMERO_DOC_ID_AMD,8,'0')
		WHEN A.TIPO_DOC_ID_AMD = 'RUC' THEN LPAD(A.NUMERO_DOC_ID_AMD,11,'0')
		WHEN A.TIPO_DOC_ID_AMD = 'P' THEN LPAD(A.NUMERO_DOC_ID_AMD,12,'0')
		ELSE A.NUMERO_DOC_ID_AMD
	END NUMERO_DOCUMENTO
	,case when b.subscriber_key is not null then 'SI' 
		ELSE 'NO' 
	END TUPS
	,DOS.DISTRICT_DESC AS DISTRITO
	,DOS.CITY_DESC AS PROVINCIA
	,DOS.DEPARTMENT_DESC AS DEPARTAMENTO
	,CASE 
		WHEN A.TIPO_PLAN = 'FIJA' THEN TRIM(D.DRE_TIP_CAL_ATI_CD) || ' ' || TRIM(D.DRE_NOM_CAL_DS) || ' ' || TRIM(D.DRE_NUM_CAL_NU)
			ELSE C.ADDRESS_LINE_1
		END 
		||  TRIM(COALESCE( ', ' || DOS.DISTRICT_DESC,'')) 
		|| TRIM(COALESCE(  ', ' ||  DOS.CITY_DESC,'')) 
		|| ' ' || TRIM(COALESCE(DOS.DEPARTMENT_DESC,''))  AS DIRECCION_TXT
	from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002 a
	left join PE_DESA_REG_STAGE.TMP_EM_MTCVAL_004 b
		ON a.subscriber_key = b.subscriber_key
	LEFT JOIN 
	( 
		SELECT X.ADDRESS_KEY, A.DISTRICT_KEY,A.DISTRICT_DESC,B.CITY_DESC,C.DEPARTMENT_DESC 
		FROM PE_PROD_LZ_DATA.ALDM_ADDRESS X 
		LEFT JOIN PE_PROD_LZ_DATA.ALDM_DISTRICT A 
			ON X.DISTRICT_KEY=A.DISTRICT_KEY 
		LEFT JOIN PE_PROD_LZ_DATA.ALDM_CITY B 
			ON A.CITY_KEY=B.CITY_KEY 
		LEFT JOIN PE_PROD_LZ_DATA.ALDM_DEPARTMENT C 
			ON B.DEPARTMENT_KEY=C.DEPARTMENT_KEY
	) DOS 
		ON A.DIRECCION = DOS.ADDRESS_KEY
	LEFT JOIN PE_PROD_LZ_DATA.ALDM_ADDRESS C 
		ON A.DIRECCION = C.ADDRESS_KEY 
	LEFT JOIN PE_PROD_LZ_DATA.SCDREC D 
		ON A.DIRECCION = D.DRE_COD_DIR_CD
	
)WITH DATA PRIMARY INDEX(NUMERO_TELEFONICO,SUBSCRIBER_KEY);

drop table PE_DESA_REG_STAGE.TMP_EM_MTCVAL_006;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_006  AS
(
 
	select * from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_005
		Qualify(row_number() over (partition by numero_Telefonico 
				order by original_activation_date desc, subscriber_Status_date desc,activation_date desc ))=1
	 
)WITH DATA  PRIMARY INDEX(NUMERO_TELEFONICO);

drop table PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007  AS
(
select a.*,COALESCE(b.subscriber_key,A.subscriber_key ) subscriber_key_ant
,b.subscriber_Status_date subscriber_Status_date_ant 
,b.subscriber_status_key subscriber_status_key_ant
,case when b.subscriber_key is not null then 'SI' 
	else 'NO' 
END TIENE_ANT
from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_006 a
left join PE_DESA_REG_STAGE.TMP_EM_MTCVAL_005 b
	on a.numero_Telefonico = b.numero_Telefonico
		and a.original_activation_date = b.original_activation_date
--and a.subscriber_key <> b.subscriber_key
where 1=1

---and a.numero_Telefonico = '974016329' 
)WITH DATA  PRIMARY INDEX(NUMERO_TELEFONICO);
 
---SELECT * FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007 
--DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_008;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_008  AS
(
select 
X.NUMERO_tELEFONICO 
,a.subscriber_key
,A.CUSTOMER_KEY
--,X.TIENE_ANT
,a.order_action_key
,a.order_key
,c.ORDER_ITEM_TYPE_DESC
,c.order_Action_type_id
,B.ORDER_START_DATE
,a.ORDER_ACTION_START_DATE       
,a.ORDER_ACTION_COMPLETED_DATE   
,a.ORDER_ACTION_STATUS_DATE
,A.REASON_FREE_TEXT
,A.ORDER_ACTION_REASON_KEY
,D.ORDER_ACTION_REASON_DESC
,A.ORDER_SALES_CHANNEL_KEY
,E.SALES_CHANNEL_NAME
--,A.SALES_CODE
---,a.*
from PE_PROD_LZ_DATA.ALDM_ORDER_ACTION a 
inner join PE_DESA_REG_STAGE.TMP_EM_MTCVAL_002 X
	ON a.subscriber_key = X.subscriber_key
inner join PE_PROD_LZ_DATA.ALDM_ODS_ORDER b
	ON a.order_key = b.order_key 
inner join pe_prod_esl_view.VW_ALDM_OrderActionType c
	ON a.order_action_type_key = c.order_action_type_key
LEFT join pe_prod_esl_view.VW_ALDM_OrderActionReason D
	ON a.ORDER_ACTION_REASON_KEY = D.ORDER_ACTION_REASON_KEY
LEFT JOIN pe_prod_esl_view.VW_ALDM_SalesServiceChannel   E
	ON A.ORDER_SALES_CHANNEL_KEY = E.SALES_SERVICE_CHANNEL_KEY
WHERE 1=1
--and a.subscriber_key in  ('193884516','196999382')
	AND B.ORDER_STATUS_KEY = '1384'
	AND A.ORDER_ACTION_STATUS_KEY ='1426'
	AND  C.order_Action_type_id  IN ('CE','ES')
	
)WITH DATA  PRIMARY INDEX(NUMERO_TELEFONICO,subscriber_key,order_action_key);

 ---pe_prod_esl_view.VW_ALDM_OrderActionType 

DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_009;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_009  AS 
(

SELECT TIENE_ANT,B.SUBSCRIBER_STATUS_dESC,a.*
FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_008 A 
INNER JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007 B
	ON A.SUBSCRIBER_KEY   =B.SUBSCRIBER_KEY_ANT
		AND A.CUSTOMER_KEY = B.CUSTOMER_KEY
--- WHERE A.NUMERO_TELEFONICO = '971982824'

)WITH DATA PRIMARY INDEX(NUMERO_TELEFONICO,subscriber_key,order_action_key);

--SELECT DISTINCT TIPO_DOCUMENTO  FROM PE_PROD_REG_DATA.T_LLAMAL_OUT_RUREPORTE_D 

DROP TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010;
CREATE TABLE PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010  AS (
	select DISTINCT 
	--A.SUBSCRIBER_KEY
	A.NUMERO_TELEFONICO
	,TUPS
	,TRIM(B.NOMBRE_TITULAR) NOMBRE_TITULAR
	,CASE WHEN B.TIPO_DOCUMENTO = 'D' THEN 'DNI'
		WHEN B.TIPO_DOCUMENTO = 'R' THEN 'RUC'
		WHEN B.TIPO_DOCUMENTO = 'C' THEN 'CE'
		ELSE B.TIPO_DOCUMENTO
	END TIPO_DOCUMENTO
	--,B.NUMERO_DOCUMENTO
	,A.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO
	,OREPLACE(A.DIRECCION_TXT,',,,,,',',') AS DIRECCION
	,CAST(A.original_activation_date AS DATE) FECHA_ALTA
	,CASE WHEN A.SUBSCRIBER_STATUS_DESC = 'Active' then 'ACTIVO'
			WHEN lower(A.SUBSCRIBER_STATUS_DESC) LIKE '%sus%' then 'SUSPENDIDO'
			else 'BAJA' end ESTADO_ACTUAL
	,CAST(SUBSCRIBER_STATUS_DATE AS DATE) FECHA_ESTADO_ACTUAL 
	,CASE WHEN C.ORDER_ACTION_START_DATE  IS NOT NULL THEN  CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) END FECHA_DE_BAJA
	,CASE WHEN C.ORDER_ACTION_START_DATE  IS NOT NULL THEN  CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) END  FECHA_DE_SUSPENSION
	,CASE WHEN C.ORDER_ACTION_START_DATE  IS NOT NULL THEN  CAST(TO_DATE(B.FECHA_FIN_SUSPENCION,'DDMMYYYY') AS DATE) END FECHA_TERMINO_SUSPENSION
	,CASE WHEN C.ORDER_ACTION_START_DATE  IS NOT NULL THEN  CAST(TO_DATE(B.FECHA_REACTIVACION_SUSPENCION,'DDMMYYYY') AS DATE) END  FECHA_DE_REACTIVACION
	,C.ORDER_ACTION_START_DATE 
	,C.ORDER_ACTION_KEY
	,C.ORDER_KEY
	,CAST(C.ORDER_ACTION_START_DATE AS DATE)  -  CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) DIAS_BAJA
	,1 FLAG_LLAMALI
	from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007 A
	INNER JOIN PE_PROD_REG_DATA.T_LLAMAL_OUT_RUREPORTE_D B
	ON A.NUMERO_TELEFONICO  = B.NUMERO_TELEFONICO  
		AND A.NUMERO_DOCUMENTO = B.NUMERO_DOCUMENTO
		AND COALESCE(B.FECHA_INICIO_SUSPENCION,'') <>''
	LEFT JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_009 C
	ON A.NUMERO_TELEFONICO = C.NUMERO_TELEFONICO
	AND CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE)  = CAST(C.ORDER_ACTION_START_DATE AS DATE)  
	AND C.ORDER_aCTION_TYPE_ID = 'CE'
)WITH DATA PRIMARY INDEX(NUMERO_TELEFONICO);

DELETE FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010
WHERE FECHA_DE_SUSPENSION IS   NULL
AND NUMERO_TELEFONICO IN(
SELECT NUMERO_TELEFONICO FROM  PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 B
WHERE  B.FECHA_DE_SUSPENSION IS NOT NULL);

---SELECT * FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 
select DISTINCT 
	A.NUMERO_TELEFONICO
	,A.TUPS
	,TRIM(B.NOMBRE_TITULAR) NOMBRE_TITULAR
	,CASE WHEN B.TIPO_DOCUMENTO = 'D' THEN 'DNI'
		WHEN B.TIPO_DOCUMENTO = 'R' THEN 'RUC'
		WHEN B.TIPO_DOCUMENTO = 'C' THEN 'CE'
		ELSE B.TIPO_DOCUMENTO
	END TIPO_DOCUMENTO
	--,B.NUMERO_DOCUMENTO
	,A.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO
	,OREPLACE(A.DIRECCION_TXT,',,,,,',',') AS DIRECCION
	,CAST(A.original_activation_date AS DATE) FECHA_ALTA
	,CASE WHEN A.SUBSCRIBER_STATUS_DESC = 'Active' then 'ACTIVO'
			WHEN lower(A.SUBSCRIBER_STATUS_DESC) LIKE '%sus%' then 'SUSPENDIDO'
			else 'BAJA' end ESTADO_ACTUAL
	,CAST(SUBSCRIBER_STATUS_DATE AS DATE) FECHA_ESTADO_ACTUAL 
	,CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) FECHA_DE_BAJA
	,CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) FECHA_DE_SUSPENSION
	,CAST(TO_DATE(B.FECHA_FIN_SUSPENCION,'DDMMYYYY') AS DATE) FECHA_TERMINO_SUSPENSION
	,CAST(TO_DATE(B.FECHA_REACTIVACION_SUSPENCION,'DDMMYYYY') AS DATE) FECHA_DE_REACTIVACION
	,C.ORDER_ACTION_START_DATE 
	,C.ORDER_ACTION_KEY
	,C.ORDER_KEY
	,CAST(C.ORDER_ACTION_START_DATE AS DATE)  -  CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) DIAS_BAJA
	,2 FLAG_LLAMALI
	from PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007 A
	INNER JOIN PE_PROD_REG_DATA.T_LLAMAL_OUT_RUREPORTE_D B
	ON A.NUMERO_TELEFONICO  = B.NUMERO_TELEFONICO  AND A.NUMERO_DOCUMENTO = B.NUMERO_DOCUMENTO
	AND COALESCE(B.FECHA_INICIO_SUSPENCION,'') <>''
	LEFT JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_009 C
	ON A.NUMERO_TELEFONICO = C.NUMERO_TELEFONICO
	AND CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE)  BETWEEN  CAST(C.ORDER_ACTION_START_DATE AS DATE)  -5
																		AND  CAST(C.ORDER_ACTION_START_DATE AS DATE)  
																		AND C.ORDER_aCTION_TYPE_ID = 'CE'
	LEFT JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 D
	ON A.NUMERO_TELEFONICO = D.NUMERO_TELEFONICO
	and CAST(TO_DATE(B.FECHA_INICIO_SUSPENCION,'DDMMYYYY') AS DATE) = d.FECHA_DE_SUSPENSION
	AND coalesce(D.DIAS_BAJA,1) = 0
	WHERE D.NUMERO_TELEFONICO IS NULL;

---	SELECT * FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010
--SELECT * FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007
INSERT INTO PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 
(NUMERO_TELEFONICO,TUPS,NOMBRE_TITULAR,TIPO_DOCUMENTO,NUMERO_DOCUMENTO,
DIRECCION,FECHA_ALTA,ESTADO_ACTUAL,FECHA_ESTADO_ACTUAL,FLAG_LLAMALI)
	select DISTINCT 
	A.NUMERO_TELEFONICO
	,B.TUPS
	,trim(B.NOMBRES_AMD)||' '||trim(B.APELLIDOS_AMD)  AS NOMBRE_TITULAR
	,B.TIPO_DOC_ID_AMD AS TIPO_DOCUMENTO
	--,B.NUMERO_DOCUMENTO
	,B.NUMERO_DOCUMENTO
	,OREPLACE(DIRECCION_TXT,',,,,,',',') AS DIRECCION_TXT
	,CAST(B.original_activation_date AS DATE) FECHA_ALTA
	,CASE WHEN B.SUBSCRIBER_STATUS_DESC = 'Active' then 'ACTIVO'
			WHEN lower(B.SUBSCRIBER_STATUS_DESC) LIKE '%sus%' then 'SUSPENDIDO'
			WHEN  SUBSCRIBER_STATUS_DESC  IS NOT NULL THEN  'BAJA' end ESTADO_ACTUAL
	,CAST(SUBSCRIBER_STATUS_DATE AS DATE) FECHA_ESTADO_ACTUAL  
	,0 FLAG_LLAMALI 
	FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_001 A
	LEFT JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_007 B
	ON A.NUMERO_TELEFONICO = B.NUMERO_TELEFONICO
	LEFT JOIN PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 C
	ON A.NUMERO_TELEFONICO = C.NUMERO_TELEFONICO
	WHERE C.NUMERO_TELEFONICO IS NULL;


 
--EXPORTAR

SELECT   NUMERO_TELEFONICO,TUPS ES_TUPS, NOMBRE_TITULAR,TIPO_DOCUMENTO,NUMERO_DOCUMENTO,DIRECCION
FECHA_ALTA, ESTADO_ACTUAL,FECHA_ESTADO_ACTUAL,FECHA_DE_BAJA,FECHA_DE_SUSPENSION,FECHA_TERMINO_SUSPENSION 
,FECHA_DE_REACTIVACION 
  FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 
where flag_llamali <> 2 ORDER BY ES_TUPS DESC,flag_llamali DESC,NUMERO_TELEFONICO,FECHA_DE_SUSPENSION  DESC

SELECT NUMERO_TELEFONICO,TUPS ES_TUPS, NOMBRE_TITULAR,TIPO_DOCUMENTO,NUMERO_DOCUMENTO,DIRECCION
FECHA_ALTA, ESTADO_ACTUAL,FECHA_ESTADO_ACTUAL,FECHA_DE_BAJA,FECHA_DE_SUSPENSION,FECHA_TERMINO_SUSPENSION 
,FECHA_DE_REACTIVACION ,ORDER_KEY, ORDER_ACTION_KEY, ORDER_ACTION_START_DATE,DIAS_BAJA DIAS_DESPUES
  FROM PE_DESA_REG_STAGE.TMP_EM_MTCVAL_010 
where flag_llamali = 2 ORDER BY ES_TUPS DESC,flag_llamali DESC,NUMERO_TELEFONICO,FECHA_DE_SUSPENSION  DESC
