REPLACE VIEW PE_DESA_REG_VIEW.VW_MTCIDENLINEA_H AS
SELECT * FROM PE_DESA_REG_DATA.T_MTCIDENLINEA_H
where flag_llamali <> 'OB'
and cast(fecha_ejecucion as date) = current_Date;

REPLACE VIEW PE_DESA_REG_VIEW.VW_MTCIDENLINEA_OBSERVADOS_H AS
SELECT NUMERO_TELEFONICO,TUPS ES_TUPS, NOMBRE_TITULAR,TIPO_DOCUMENTO,NUMERO_DOCUMENTO,DIRECCION,
FECHA_ALTA, ESTADO_ACTUAL,FECHA_ESTADO_ACTUAL,FECHA_DE_BAJA,FECHA_DE_SUSPENSION,FECHA_TERMINO_SUSPENSION 
,FECHA_DE_REACTIVACION ,ORDER_KEY, ORDER_ACTION_KEY, ORDER_ACTION_START_DATE,DIAS_BAJA DIAS_DESPUES
 FROM PE_DESA_REG_DATA.T_MTCIDENLINEA_H
where flag_llamali = 'OB'
and cast(fecha_ejecucion as date) = current_Date;